### ISSUE TITLE
Не работает или нужны прокси/VPN?

### ISSUE THREAD

**Issue by shadow-ru** [ryzed/flibusta-calibre-opds-store#1]
Здравствуйте,

Спасибо за плагин. А он сейчас работает? У меня на 5.31 и 5.42 не завелось. Может, ему прокси/VPN нужен для доступа к flibusta.is?

**Comment by ryzed** [comment]
Добрый день.

Давно не проверял, если честно.
Если подобный URL в браузере открывается [http://flibusta.is/opds/opensearch?searchTerm=warhammer](http://flibusta.is/opds/opensearch?searchTerm=warhammer) значит сломался плагин.
Если не открывается, значит нужен прокси.
У меня URL открывается.

Проверил сейчас сам плагин, работает.
<img width="1727" alt="NVIDIA_Share_0fFghivk6q" src="https://user-images.githubusercontent.com/1711255/169615418-1c3c09af-92e2-4b02-bb4f-36de69f86d3b.png">

**Comment by shadow-ru** [comment]
Да, с ВПН этот URL открывается. Без него -- нет.
