### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by v1n1p00h** [ryzed/flibusta-calibre-opds-store#2]
Привет ryzed,

Попытался использовать твой плагин для Калибра, но ничего не получаю на свои запросы. 
Я вводил и наывания книг, и имена/фамилии  авторов, и протсто ключевые слова - все без толку.
Это проблемы с плагином или истичником?

Заранее большое спасибо за любую помошь.

С уважением,
 v1n1p00h

**Comment by ryzed** [comment]
Добрый день,

Если подобный URL в браузере открывается http://flibusta.is/opds/opensearch?searchTerm=warhammer значит сломался плагин.
Если не открывается, значит нужен прокси или что-то с сайтом.
Сейчас у меня http://flibusta.is/ не открывается, так что плагин работать не будет.

**Comment by v1n1p00h** [comment]
Спасибо! Все понятно.
