### ISSUE TITLE
Скомпилируйте пожалуйста плагин версии flibusta-calibre-opds-store-0.0.2

### ISSUE THREAD

**Issue by makovroman** [ryzed/flibusta-calibre-opds-store#5]
Он скачивается Source code, и по этому Calibre его не видит, с первой версией все ОК.

calibre 7.5.1  embedded-python: True
macOS-14.2.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.2.0', 'Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64')
Python 3.11.5
OSX: ('14.2.1', ('', '', ''), 'x86_64')
Interface language: ru
EXE path: /Applications/calibre.app/Contents/MacOS/calibre
Successfully initialized third party plugins: KOReader Sync (0, 5, 2) && Флибуста (1, 0, 1)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 513, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 299, in load
  File "calibre/customize/zipplugin.py", line 394, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Users/roman/Desktop/flibusta-calibre-opds-store-0.0.2.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ryzed** [comment]
Привет.
Релиз это просто директория src в зипке.
Добавил. https://github.com/ryzed/flibusta-calibre-opds-store/releases/download/0.0.2/flibusta-calibre-opds-store-0.0.2.zip
